### ISSUE TITLE
Apple Music no album art

### ISSUE THREAD

**Issue by L-Ratio** [tjhrulz/WebNowPlaying-BrowserExtension#75]
Referring to #72 

I have downloaded the new plugin version and side loaded the new extension version but same thing is happening if needed I can provide more of the apple music album art code
1st error that appeared 
```
ERRO (20:35:21.029) : Unable to get album art from: .jpg/2000x2000.jpg
DBUG (20:35:21.032) : System.UriFormatException: Invalid URI: The format of the URI could not be determined.

   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)

   at System.Net.WebRequest.Create(String requestUriString)

   at WebNowPlaying.Measure.GetImageFromUrl(String id, String url)

```
2nd error that appears everytime a new song plays
```
ERRO (20:39:10.109) : WebNowPlaing.dll - Error converting duration into integer
DBUG (20:39:10.110) : System.FormatException: Input string was not in a correct format.

   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)

   at System.Int16.Parse(String s, NumberStyles style, NumberFormatInfo info)

   at WebNowPlaying.Measure.WebNowPlaying.OnMessage(MessageEventArgs arg)
```

**Comment by tjhrulz** [comment]
There is no need to Open a duplicate for an unfixed problem, I reopened the original issue.
